In [3]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\suriy\OneDrive\Desktop\employees.csv")
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50

In [8]:
#high salary
hs=df[df['SALARY']>5000]
hs

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50

In [10]:
avg=df.groupby('DEPARTMENT_ID')['SALARY'].mean()
avg

DEPARTMENT_ID
10      4400.000000
20      9500.000000
30      4150.000000
40      6500.000000
50      3721.739130
60      5760.000000
70     10000.000000
90     19333.333333
100     8601.333333
110    10154.000000
Name: SALARY, dtype: float64

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     50 non-null     int64
 1   FIRST_NAME      50 non-null     str
 2   LAST_NAME       50 non-null     str
 3   EMAIL           50 non-null     str
 4   PHONE_NUMBER    50 non-null     str
 5   HIRE_DATE       50 non-null     str
 6   JOB_ID          50 non-null     str
 7   SALARY          50 non-null     int64
 8   COMMISSION_PCT  50 non-null     str
 9   MANAGER_ID      50 non-null     str
 10  DEPARTMENT_ID   50 non-null     int64
dtypes: int64(3), str(8)
memory usage: 4.4 KB

In [14]:
sorted_df = df.sort_values(by="JOB_ID")
sorted_df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
8,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,-,205,110
7,205,Shelley,Higgins,SHIGGINS,515.123.8080,07-JUN-02,AC_MGR,12008,-,101,110
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
9,100,Steven,King,SKING,515.123.4567,17-JUN-03,AD_PRES,24000,-,-,90
10,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21-SEP-05,AD_VP,17000,-,100,90
11,102,Lex,De Haan,LDEHAAN,515.123.4569,13-JAN-01,AD_VP,17000,-,100,90
19,110,John,Chen,JCHEN,515.124.4269,28-SEP-05,FI_ACCOUNT,8200,-,108,100
18,109,Daniel,Faviet,DFAVIET,515.124.4169,16-AUG-02,FI_ACCOUNT,9000,-,108,100
22,113,Luis,Popp,LPOPP,515.124.4567,07-DEC-07,FI_ACCOUNT,6900,-,108,100
20,111,Ismael,Sciarra,ISCIARRA,515.124.4369,30-SEP-05,FI_ACCOUNT,7700,-,108,100
21,112,Jose Manuel,Urman,JMURMAN,515.124.4469,07-MAR-06,FI_ACCOUNT,7800,-,108,100
17,108,Nancy,Greenberg,NGREENBE,515.124.4569,17-AUG-02,FI_MGR,12008,-,101,100
5,203,Susan,Mavris,SMAVRIS,515.123.7777,07-JUN-02,HR_REP,6500,-,101,40
12,103,Alexander,Hunold,AHUNOLD,590.423.4567,03-JAN-06,IT_PROG,9000,-,102,60
14,105,David,Austin,DAUSTIN,590.423.4569,25-JUN-05,IT_PROG,4800,-,103,60
15,106,Valli,Pataballa,VPATABAL,590.423.4560,05-FEB-06,IT_PROG,4800,-,103,60
16,107,Diana,Lorentz,DLORENTZ,590.423.5567,07-FEB-07,IT_PROG,4200,-,103,60
13,104,Bruce,Ernst,BERNST,590.423.4568,21-MAY-07,IT_PROG,6000,-,103,60
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20
6,204,Hermann,Baer,HBAER,515.123.8888,07-JUN-02,PR_REP,10000,-,101,70
27,118,Guy,Himuro,GHIMURO,515.127.4565,15-NOV-06,PU_CLERK,2600,-,114,30
24,115,Alexander,Khoo,AKHOO,515.127.4562,18-MAY-03,PU_CLERK,3100,-,114,30
28,119,Karen,Colmenares,KCOLMENA,515.127.4566,10-AUG-07,PU_CLERK,2500,-,114,30
25,116,Shelli,Baida,SBAIDA,515.127.4563,24-DEC-05,PU_CLERK,2900,-,114,30
26,117,Sigal,Tobias,STOBIAS,515.127.4564,24-JUL-05,PU_CLERK,2800,-,114,30
23,114,Den,Raphaely,DRAPHEAL,515.127.4561,07-DEC-02,PU_MAN,11000,-,100,30
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
47,138,Stephen,Stiles,SSTILES,650.121.2034,26-OCT-05,ST_CLERK,3200,-,123,50
46,137,Renske,Ladwig,RLADWIG,650.121.1234,14-JUL-03,ST_CLERK,3600,-,123,50
45,136,Hazel,Philtanker,HPHILTAN,650.127.1634,06-FEB-08,ST_CLERK,2200,-,122,50
44,135,Ki,Gee,KGEE,650.127.1734,12-DEC-07,ST_CLERK,2400,-,122,50
43,134,Michael,Rogers,MROGERS,650.127.1834,26-AUG-06,ST_CLERK,2900,-,122,50
42,133,Jason,Mallin,JMALLIN,650.127.1934,14-JUN-04,ST_CLERK,3300,-,122,50
41,132,TJ,Olson,TJOLSON,650.124.8234,10-APR-07,ST_CLERK,2100,-,121,50
40,131,James,Marlow,JAMRLOW,650.124.7234,16-FEB-05,ST_CLERK,2500,-,121,50
39,130,Mozhe,Atkinson,MATKINSO,650.124.6234,30-OCT-05,ST_CLERK,2800,-,121,50
38,129,Laura,Bissot,LBISSOT,650.124.5234,20-AUG-05,ST_CLERK,3300,-,121,50
37,128,Steven,Markle,SMARKLE,650.124.1434,08-MAR-08,ST_CLERK,2200,-,120,50
36,127,James,Landry,JLANDRY,650.124.1334,14-JAN-07,ST_CLERK,2400,-,120,50
35,126,Irene,Mikkilineni,IMIKKILI,650.124.1224,28-SEP-06,ST_CLERK,2700,-,120,50
34,125,Julia,Nayer,JNAYER,650.124.1214,16-JUL-05,ST_CLERK,3200,-,120,50
48,139,John,Seo,JSEO,650.121.2019,12-FEB-06,ST_CLERK,2700,-,123,50
49,140,Joshua,Patel,JPATEL,650.121.1834,06-APR-06,ST_CLERK,2500,-,123,50
33,124,Kevin,Mourgos,KMOURGOS,650.123.5234,16-NOV-07,ST_MAN,5800,-,100,50
32,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10-OCT-05,ST_MAN,6500,-,100,50
31,122,Payam,Kaufling,PKAUFLIN,650.123.3234,01-MAY-03,ST_MAN,7900,-,100,50
30,121,Adam,Fripp,AFRIPP,650.123.2234,10-APR-05,ST_MAN,8200,-,100,50
29,120,Matthew,Weiss,MWEISS,650.123.1234,18-JUL-04,ST_MAN,8000,-,100,50

In [15]:
manager_count = df["MANAGER_ID"].value_counts()
manager_count

MANAGER_ID
100    9
101    5
108    5
114    5
103    4
120    4
121    4
122    4
123    4
124    2
201    1
205    1
 -     1
102    1
Name: count, dtype: int64

In [2]:
import pandas as pd

# Monthly Sales Data
data = {
    "Month": ["January", "February", "March", "April", "May", "June"],
    "Sales": [45000, 52000, 48000, 61000, 55000, 67000]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Monthly Sales Data")
print(df)

print("\nData Aggregation")

# Total Sales
print("Total Sales:", df["Sales"].sum())

# Average Sales
print("Average Sales:", df["Sales"].mean())

# Maximum Sales
print("Maximum Sales:", df["Sales"].max())

# Minimum Sales
print("Minimum Sales:", df["Sales"].min())

Monthly Sales Data
      Month  Sales
0   January  45000
1  February  52000
2     March  48000
3     April  61000
4       May  55000
5      June  67000

Data Aggregation
Total Sales: 328000
Average Sales: 54666.666666666664
Maximum Sales: 67000
Minimum Sales: 45000

In [3]:
import pandas as pd

# Employee Data
data = {
    "Employee_ID": [101,102,103,104,105,106,107,108],
    "Employee_Name": [
        "John","Alice","David","Mary",
        "James","Robert","Linda","Sophia"
    ],
    "Department": [
        "HR","IT","IT","Finance",
        "HR","Finance","IT","HR"
    ],
    "Salary": [
        35000,50000,55000,60000,
        40000,65000,52000,45000
    ]
}

df = pd.DataFrame(data)

print("Employee Details")
print(df)

# Group by Department
result = df.groupby("Department").agg(
    Total_Salary=("Salary","sum"),
    Average_Salary=("Salary","mean"),
    Employee_Count=("Salary","count")
)

print("\nDepartment-wise Salary Details")
print(result)

Employee Details
   Employee_ID Employee_Name Department  Salary
0          101          John         HR   35000
1          102         Alice         IT   50000
2          103         David         IT   55000
3          104          Mary    Finance   60000
4          105         James         HR   40000
5          106        Robert    Finance   65000
6          107         Linda         IT   52000
7          108        Sophia         HR   45000

Department-wise Salary Details
            Total_Salary  Average_Salary  Employee_Count
Department
Finance           125000    62500.000000               2
HR                120000    40000.000000               3
IT                157000    52333.333333               3

In [4]:
import pandas as pd

# Employees Data
employees = {
    "Employee_ID": [101,102,103,104,105],
    "Employee_Name": [
        "John","Alice","David","Mary","James"
    ],
    "Department_ID": [10,20,30,20,10],
    "Salary": [35000,50000,45000,60000,40000]
}

# Departments Data
departments = {
    "Department_ID": [10,20,30],
    "Department_Name": [
        "HR",
        "IT",
        "Finance"
    ]
}

# Create DataFrames
emp_df = pd.DataFrame(employees)
dept_df = pd.DataFrame(departments)

print("Employees Data")
print(emp_df)

print("\nDepartments Data")
print(dept_df)

# Merge DataFrames
merged_df = pd.merge(emp_df, dept_df, on="Department_ID")

print("\nMerged Data")
print(merged_df)

Employees Data
   Employee_ID Employee_Name  Department_ID  Salary
0          101          John             10   35000
1          102         Alice             20   50000
2          103         David             30   45000
3          104          Mary             20   60000
4          105         James             10   40000

Departments Data
   Department_ID Department_Name
0             10              HR
1             20              IT
2             30         Finance

Merged Data
   Employee_ID Employee_Name  Department_ID  Salary Department_Name
0          101          John             10   35000              HR
1          102         Alice             20   50000              IT
2          103         David             30   45000         Finance
3          104          Mary             20   60000              IT
4          105         James             10   40000              HR