In [7]:
# modules we'll use
import pandas as pd
import numpy as np

# read in all our data
df = pd.read_csv("data_cleaning.csv")

print(df.head(10))
# set seed for reproducibility
np.random.seed(0)

   Employee_ID   Name   Age   Salary Joining_Date Department        City
0          101   John  25.0  35000.0   2022-01-12         HR     Chennai
1          102  Anita  28.0  42000.0   2022-02-15         IT   Bangalore
2          103  Rahul  31.0  52000.0   2022-03-20    Finance      Mumbai
3          104  Sneha  29.0  48000.0   2022-04-25      Sales       Delhi
4          105  Karan  35.0  61000.0   2022-05-18  Marketing   Hyderabad
5          106  Priya  27.0  43000.0   2022-06-10         HR        Pune
6          107   Arun  30.0  55000.0   2022-07-15         IT     Kolkata
7          108  Meena  32.0  60000.0   2022-08-08    Finance     Chennai
8          109   Ravi  26.0  39000.0   2022-09-11      Sales     Madurai
9          110   Asha  24.0  36000.0   2022-10-12  Marketing  Coimbatore

Cleaning Techniques
1. Missing Values

In [16]:
# Fill numeric columns
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

# Fill categorical columns
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])
df["Name"] = df["Name"].fillna("Unknown")

# Fill dates
df["Joining_Date"] = df["Joining_Date"].fillna(method="ffill")
df.head(10)

C:\Users\dilli\AppData\Local\Temp\ipykernel_18280\3661592560.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Joining_Date"] = df["Joining_Date"].fillna(method="ffill")

   Employee_ID   Name   Age   Salary Joining_Date Department        City
0          101   John  25.0  35000.0   2022-01-12         HR     Chennai
1          102  Anita  28.0  42000.0   2022-02-15         IT   Bangalore
2          103  Rahul  31.0  52000.0   2022-03-20    Finance      Mumbai
3          104  Sneha  29.0  48000.0   2022-04-25      Sales       Delhi
4          105  Karan  35.0  61000.0   2022-05-18  Marketing   Hyderabad
5          106  Priya  27.0  43000.0   2022-06-10         HR        Pune
6          107   Arun  30.0  55000.0   2022-07-15         IT     Kolkata
7          108  Meena  32.0  60000.0   2022-08-08    Finance     Chennai
8          109   Ravi  26.0  39000.0   2022-09-11      Sales     Madurai
9          110   Asha  24.0  36000.0   2022-10-12  Marketing  Coimbatore

2. Scaling & Normalization

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df["Salary"] = scaler.fit_transform(df[["Salary"]])
df.head(10)

   Employee_ID   Name   Age    Salary Joining_Date Department        City
0          101   John  25.0  0.070175   2022-01-12         HR     Chennai
1          102  Anita  28.0  0.094737   2022-02-15         IT   Bangalore
2          103  Rahul  31.0  0.129825   2022-03-20    Finance      Mumbai
3          104  Sneha  29.0  0.115789   2022-04-25      Sales       Delhi
4          105  Karan  35.0  0.161404   2022-05-18  Marketing   Hyderabad
5          106  Priya  27.0  0.098246   2022-06-10         HR        Pune
6          107   Arun  30.0  0.140351   2022-07-15         IT     Kolkata
7          108  Meena  32.0  0.157895   2022-08-08    Finance     Chennai
8          109   Ravi  26.0  0.084211   2022-09-11      Sales     Madurai
9          110   Asha  24.0  0.073684   2022-10-12  Marketing  Coimbatore

3. Date Cleaning

In [18]:

df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    format="mixed",
    errors="coerce"
)

#Replace invalid dates

df["Joining_Date"] = df["Joining_Date"].fillna(df["Joining_Date"].mode()[0])
df.head(10)

   Employee_ID   Name   Age    Salary Joining_Date Department        City
0          101   John  25.0  0.070175   2022-01-12         HR     Chennai
1          102  Anita  28.0  0.094737   2022-02-15         IT   Bangalore
2          103  Rahul  31.0  0.129825   2022-03-20    Finance      Mumbai
3          104  Sneha  29.0  0.115789   2022-04-25      Sales       Delhi
4          105  Karan  35.0  0.161404   2022-05-18  Marketing   Hyderabad
5          106  Priya  27.0  0.098246   2022-06-10         HR        Pune
6          107   Arun  30.0  0.140351   2022-07-15         IT     Kolkata
7          108  Meena  32.0  0.157895   2022-08-08    Finance     Chennai
8          109   Ravi  26.0  0.084211   2022-09-11      Sales     Madurai
9          110   Asha  24.0  0.073684   2022-10-12  Marketing  Coimbatore

4. Character Encoding

In [19]:
df = pd.read_csv("C:\Documents\Query_processing\data_cleaning.csv", encoding="utf-8")

df = pd.read_csv("C:\Documents\Query_processing\data_cleaning.csv", encoding="latin1")

#Remove special characters

df["Name"] = (
    df["Name"]
      .str.encode("ascii", errors="ignore")
      .str.decode("ascii")
)
df.head(10)

   Employee_ID   Name   Age   Salary Joining_Date Department        City
0          101   John  25.0  35000.0   2022-01-12         HR     Chennai
1          102  Anita  28.0  42000.0   2022-02-15         IT   Bangalore
2          103  Rahul  31.0  52000.0   2022-03-20    Finance      Mumbai
3          104  Sneha  29.0  48000.0   2022-04-25      Sales       Delhi
4          105  Karan  35.0  61000.0   2022-05-18  Marketing   Hyderabad
5          106  Priya  27.0  43000.0   2022-06-10         HR        Pune
6          107   Arun  30.0  55000.0   2022-07-15         IT     Kolkata
7          108  Meena  32.0  60000.0   2022-08-08    Finance     Chennai
8          109   Ravi  26.0  39000.0   2022-09-11      Sales     Madurai
9          110   Asha  24.0  36000.0   2022-10-12  Marketing  Coimbatore

5. Inconsistent Data Entry

In [14]:
df["Department"] = df["Department"].str.strip()

#Convert to proper case

df["Department"] = df["Department"].str.title()

#Replace abbreviations

df["Department"] = df["Department"].replace({
    "Fin.":"Finance",
    "Hr":"HR",
    "Hr":"HR",
    "hr":"HR",
    "hR":"HR",
    "It":"IT",
    "it":"IT"
})

#Remove duplicate rows

df = df.drop_duplicates()

#Remove duplicate employee IDs

df = df.drop_duplicates(subset="Employee_ID")

df

,Employee_ID,Name,Age,Salary,Joining_Date,Department,City
0,101,John,25.0,35000.0,2022-01-12,HR,Chennai
1,102,Anita,28.0,42000.0,2022-02-15,IT,Bangalore
2,103,Rahul,31.0,52000.0,2022-03-20,Finance,Mumbai
3,104,Sneha,29.0,48000.0,2022-04-25,Sales,Delhi
4,105,Karan,35.0,61000.0,2022-05-18,Marketing,Hyderabad
5,106,Priya,27.0,43000.0,2022-06-10,HR,Pune
6,107,Arun,30.0,55000.0,2022-07-15,IT,Kolkata
7,108,Meena,32.0,60000.0,2022-08-08,Finance,Chennai
8,109,Ravi,26.0,39000.0,2022-09-11,Sales,Madurai
9,110,Asha,24.0,36000.0,2022-10-12,Marketing,Coimbatore
10,111,NaN,29.0,47000.0,2022-11-15,HR,Salem
11,112,Vikram,NaN,51000.0,2022-12-18,IT,Erode
12,113,Latha,34.0,NaN,2023-01-10,Finance,Trichy
13,114,NaN,31.0,58000.0,2023-02-12,Sales,Vellore
14,115,Deepak,27.0,NaN,2023-03-14,Marketing,Tirunelveli
15,116,Divya,NaN,49000.0,2023-04-15,HR,Chennai
16,117,NaN,33.0,62000.0,2023-05-16,IT,Bangalore
17,118,Naveen,28.0,NaN,2023-06-17,Finance,Mumbai
18,119,Krishna,NaN,53000.0,2023-07-18,Sales,Delhi
19,120,NaN,26.0,45000.0,2023-08-19,Marketing,Pune
20,121,Akash,22.0,250000.0,2023-09-10,HR,Chennai
21,122,Keerthi,55.0,15000.0,2023-10-12,IT,Bangalore
22,123,Suresh,40.0,120000.0,2023-11-14,Finance,Mumbai
23,124,Harini,19.0,18000.0,2023-12-15,Sales,Delhi
24,125,Mohan,60.0,300000.0,2024-01-16,Marketing,Hyderabad
25,126,Renu,29.0,52000.0,12/02/2024,HR,Pune
26,127,Sathish,30.0,48000.0,15-Mar-2024,IT,Kolkata
27,128,Anu,26.0,45000.0,2024/04/20,Finance,Chennai
28,129,Gokul,33.0,61000.0,April 25 2024,Sales,Madurai
29,130,Sindhu,31.0,57000.0,InvalidDate,Marketing,Coimbatore
30,131,Ajay,28.0,47000.0,2024-06-12,HR,Salem
31,132,Geetha,30.0,55000.0,2024-07-13,HR,Erode
32,133,Kavin,27.0,51000.0,2024-08-14,HR,Trichy
33,134,Nisha,29.0,49000.0,2024-09-15,IT,Vellore
34,135,Prabhu,35.0,63000.0,2024-10-16,Finance,Tirunelveli
35,136,Ramesh,36.0,64000.0,2024-11-17,Sales,Chennai
36,137,Uma,24.0,42000.0,2024-12-18,Marketing,Bangalore
37,138,Bala,32.0,56000.0,2025-01-19,Finance,Mumbai
38,139,Sara,26.0,44000.0,2025-02-20,Sales,Delhi
39,140,Kishore,30.0,59000.0,2025-03-21,HR,Hyderabad
40,141,Jos,29.0,51000.0,2025-04-10,IT,Chennai
41,142,Rene,31.0,54000.0,2025-05-11,Finance,Bangalore
42,143,Mller,34.0,62000.0,2025-06-12,Sales,Mumbai
43,144,Franois,28.0,47000.0,2025-07-13,Marketing,Delhi
44,145,Anas,27.0,45000.0,2025-08-14,HR,Pune
45,146,Rohit,25.0,43000.0,2025-09-15,IT,Chennai
46,147,Neha,33.0,61000.0,2025-10-16,Finance,Bangalore
47,148,Amit,29.0,50000.0,2025-11-17,Sales,Mumbai
48,149,Pooja,30.0,56000.0,2025-12-18,Marketing,Delhi
49,150,Manoj,32.0,59000.0,2026-01-19,HR,Hyderabad