In [1]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'David'],
    'Age': [25, 30, 25, 35, 30, 40],
    'City': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Los Angeles', 'San Francisco']
}

df = pd.DataFrame(data)
df

      Name  Age           City
0    Alice   25       New York
1      Bob   30    Los Angeles
2    Alice   25       New York
3  Charlie   35        Chicago
4      Bob   30    Los Angeles
5    David   40  San Francisco

In [2]:
duplicates = df.duplicated()

duplicates

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [3]:
df_no_duplicates_columns = df.drop_duplicates(subset=['Name', 'City'])
(df_no_duplicates_columns)

      Name  Age           City
0    Alice   25       New York
1      Bob   30    Los Angeles
3  Charlie   35        Chicago
5    David   40  San Francisco